version: "3.9"
services:
  rasa:
    build: .
    container_name: rasa_server
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models  # Solo se montan modelos
    command: ["rasa", "run", "-m", "models", "--enable-api", "--cors", "*", "--debug"]
    depends_on:
      - actions

  actions:
    image: rasa/rasa-sdk:3.0.0
    container_name: rasa_actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: ["rasa", "run", "actions"]
